#include <pico/stdlib.h>
#include "hardware/pio.h"
#include "squarewave.pio.h" // generated by pio assembler


int main(){
    
    const uint pin = 5;
   
    // choose one of the three pio instances 
    PIO pio = pio0;

    //find a free state machine for the pio instance
    for(uint i = 0; i < count_of(squarewave_program_instructions); i++){
        pio->instr_mem[i] = squarewave_program_instructions[i];
    }

    pio->sm[0].clkdiv = (uint32_t) (250.0f * (1 << 16));

    pio->sm[0].pinctrl = 
        (1 << PIO_SM0_PINCTRL_SET_COUNT_LSB) | 
        (pin << PIO_SM0_PINCTRL_SET_BASE_LSB);

    gpio_set_function(pin, pio_get_funcsel(pio));

    hw_set_bits(&pio->ctrl, 1 << (PIO_CTRL_SM_ENABLE_LSB + 0));
}