#include <pico/stdlib.h>
#include "hardware/pio.h"
#include "squarewave.pio.h" // generated by pio assembler

#define SAMPLE_RATE 44100

double get_clock_div_ratio(double sample_rate){
    double channels = 2;
    double audio_bits = 16; 
    double instruction_number = 4;
    double system_clock = 150000000;
    return system_clock / (sample_rate * audio_bits * channels * instruction_number);
}


int main(){
    
    const uint pin = 5;
   
    // choose one of the three pio instances 
    PIO pio = pio0;

    //find a free state machine for the pio instance
    for(uint i = 0; i < count_of(squarewave_program_instructions); i++){
        pio->instr_mem[i] = squarewave_program_instructions[i];
    }

    //calculated this float for SAMPLE rate of 44100, audio bits of 16
    pio->sm[0].clkdiv = (uint32_t) (get_clock_div_ratio(SAMPLE_RATE) * (1 << 16));

    pio->sm[0].pinctrl = 
        (1 << PIO_SM0_PINCTRL_SET_COUNT_LSB) | 
        (pin << PIO_SM0_PINCTRL_SET_BASE_LSB);

    gpio_set_function(pin, pio_get_funcsel(pio));

    hw_set_bits(&pio->ctrl, 1 << (PIO_CTRL_SM_ENABLE_LSB + 0));
}